# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: dhkim20157/python3.7:0.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3.7 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: create secret.json
          command: |
            echo { "SECRET_KEY": "${SECRET_KEY}", "DB_PASSWORD": "${DB_PASSWORD}" } > ./secret.json

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test --with-coverage

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - deploy:
          name: deploy to aws with zappa
          command: |
            . venv/bin/activate
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
              zappa update dev
            fi
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              zappa update production
            fi